### ISSUE TITLE
Issue about project

### ISSUE THREAD

**Issue by LikiPiki** [DerFreimensch/OP_9_Lab#1]
## Issues
1. You can do this task without an extra `fout` file. Simply replace `\n` character to `' '` in main logic.
https://github.com/DerFreimensch/OP_9_Lab/blob/94bedee1f6695bef0d7aa634287aabdb8faa082b/OP_9/Code.c#L30
2. If u use the GitHub, plz name your commits so that they show what is in them.
3. Don't name variables with upper-case, because you enter this `N` in the main program. It's not a constant.
https://github.com/DerFreimensch/OP_9_Lab/blob/94bedee1f6695bef0d7aa634287aabdb8faa082b/OP_9/Code.c#L13
## Main questions:

1. What type is the file pointer?
2. Why files, which open as "w", must be closed when the program exit?
3. What is binary file mode means?
4. Modify your program to use one output file to complete this task.

You can answer these questions on the GitHub issue, and keep commits there when you complete this task. You DON'T need to edit your doc file, it is fine.

**Comment by DerFreimensch** [comment]
1) This data type defines a stream and contains information needed to control the stream, including a pointer to the stream buffer and its status indicators

**Comment by kostr-code** [comment]
1) This data type defines a stream and contains information needed to control the stream, including a pointer to the stream buffer and its status indicators
2) It's important because information may not be saved automatically
3) Writting and reading carried out in and from binary file. Information stores in such files as bites.
4)Programm was modified

**Comment by LikiPiki** [comment]
almost good, but you cannot use strings.h library. Plz do it without strings library!

**Comment by kostr-code** [comment]
Programm didn't use string.h library.  I deleted this include string in the programm and everything is worked well. Maybe I used this library in other projects and unexpted wrote it here.

**Comment by LikiPiki** [comment]
Ok, good. I sent report with sign on your mail!
